name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx build -t your-docker-username/your-app:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push your-docker-username/your-app:latest

    - name: Set up kubectl
      uses: steebchen/kubectl@v1
      with:
        version: latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/app/deployment.yaml
        kubectl apply -f k8s/app/service.yaml
        kubectl apply -f k8s/app/ingress.yaml
        kubectl apply -f k8s/app/certificate.yaml

    - name: Run Tests
      run: |
        # Add commands to run tests here
