name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx create --use
        docker buildx build -t lkapilcloud/testing:v1 --push .
        docker tag lkapilcloud/testing:v1 lkapilcloud/testing:v1        
        docker push lkapilcloud/testing:v1

    - name: Set up kubectl
      uses: steebchen/kubectl@v2.0.0
      with:
        version: latest

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install Cert-Manager
      run: |
        kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.2/cert-manager.yaml

    - name: Install nginx-ingress
      run: |
        kubectl create namespace nginx-ingress
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install nginx-ingress ingress-nginx/ingress-nginx -n nginx-ingress

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/app/deployment.yaml

    - name: Run Tests
      run: |
        # Add commands to run tests here
